"""The countries this dashboard covers (shared by app.py, prepare_model.py and pages/).

Countries were removed from the dashboard and its data on 2026-10-07 (27, including Kosovo); the historical regressions
in prepare_model.py still use the wider REGRESSION_ISO3 panel so their estimates stay as precise as before.
"""

# ISO3 code -> name shown in the dropdown
ALLOWED_COUNTRIES = {
    "AGO": "Angola",
    "AZE": "Azerbaijan",
    "BGD": "Bangladesh",
    "BLZ": "Belize",
    "BEN": "Benin",
    "BOL": "Bolivia",
    "BWA": "Botswana",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "KHM": "Cambodia",
    "CMR": "Cameroon",
    "CAF": "Central African Republic",
    "CIV": "Cote d'Ivoire",
    "COD": "Democratic Republic of the Congo",
    "DJI": "Djibouti",
    "DOM": "Dominican Republic",
    "EGY": "Egypt",
    "SLV": "El Salvador",
    "SWZ": "Eswatini",
    "ETH": "Ethiopia",
    "FJI": "Fiji",
    "GMB": "Gambia",
    "GHA": "Ghana",
    "GTM": "Guatemala",
    "GIN": "Guinea",
    "GUY": "Guyana",
    "HTI": "Haiti",
    "HND": "Honduras",
    "IND": "India",
    "IDN": "Indonesia",
    "IRQ": "Iraq",
    "JAM": "Jamaica",
    "JOR": "Jordan",
    "KEN": "Kenya",
    "KGZ": "Kyrgyzstan",
    "LAO": "Laos",
    "LSO": "Lesotho",
    "LBR": "Liberia",
    "LBY": "Libya",
    "MDG": "Madagascar",
    "MWI": "Malawi",
    "MLI": "Mali",
    "MUS": "Mauritius",
    "MDA": "Moldova",
    "MNG": "Mongolia",
    "MOZ": "Mozambique",
    "NAM": "Namibia",
    "NPL": "Nepal",
    "NIC": "Nicaragua",
    "NER": "Niger",
    "NGA": "Nigeria",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PNG": "Papua New Guinea",
    "PHL": "Philippines",
    "RWA": "Rwanda",
    "STP": "Sao Tome and Principe",
    "SEN": "Senegal",
    "SLE": "Sierra Leone",
    "SOM": "Somalia",
    "ZAF": "South Africa",
    "SSD": "South Sudan",
    "TJK": "Tajikistan",
    "TZA": "Tanzania",
    "TLS": "Timor-Leste",
    "TGO": "Togo",
    "UGA": "Uganda",
    "VEN": "Venezuela",
    "VNM": "Vietnam",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
}


def dropdown_countries() -> dict:
    """ISO3 -> name for the dropdowns, in alphabetical order of name."""
    return dict(sorted(ALLOWED_COUNTRIES.items(), key=lambda kv: kv[1]))
